misconfigurations:
  - id: AVD-DS-0002
    statement: fix after introducing trivy scanning
    expired_at: 2026-03-15
vulnerabilities:
  - id: CVE-2025-68121
    statement: fix after introducing trivy scanning
    expired_at: 2026-03-10
