version: 2
updates:

 # Enable version updates for docker on service-front web
  - package-ecosystem: "docker"
    directory: "/service-front/docker/web"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1

 # Enable version updates for docker on service-front app
  - package-ecosystem: "docker"
    directory: "/service-front/docker/app"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1

  # Enable version updates for docker on service-api web
  - package-ecosystem: "docker"
    directory: "/service-api/docker/web"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1

 # Enable version updates for docker on service-api app
  - package-ecosystem: "docker"
    directory: "/service-api/docker/app"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1

  # Enable version updates for docker on service-admin web
  - package-ecosystem: "docker"
    directory: "/service-admin/docker/web"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1

 # Enable version updates for docker on service-admin app
  - package-ecosystem: "docker"
    directory: "/service-admin/docker/app"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1

  # Enable version updates for docker on cypress
  - package-ecosystem: "docker"
    directory: "/cypress"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1


  # Enable version updates for docker on tests
  - package-ecosystem: "docker"
    directory: "/tests"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1

  # Enable version updates for docker on tests/pa11y
  - package-ecosystem: "docker"
    directory: "/tests/pa11y"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 1
